// Compatibility runner for Botmux 3.18.14's bundled PM2 startup failure.
// Uses the service descriptor and gateway token generated by Botmux itself.
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { createServer } from 'node:net';
import { homedir } from 'node:os';
import { resolve } from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { loadRuntime } from './runtime.js';

const pluginHome = resolve(homedir(), '.botmux/plugins/card-confirmation');
const metadataPath = resolve(pluginHome, 'service.json');
const stateDir = loadRuntime().stateDir;
mkdirSync(stateDir, { recursive: true });
const lock = resolve(stateDir, 'local-service.lock');
writeFileSync(lock, String(process.pid), { flag: 'wx', mode: 0o600 });

let child: ReturnType<typeof spawn> | undefined;
let childExit: Promise<number | null> | undefined;

function cleanup(): void {
  if (existsSync(metadataPath)) {
    const state = JSON.parse(readFileSync(metadataPath, 'utf8')) as { pid?: number };
    if (child?.pid && state.pid === child.pid) rmSync(metadataPath);
  }
  rmSync(lock, { force: true });
}

interface Pm2Descriptor {
  apps: Array<{
    name: string;
    script: string;
    cwd: string;
    env: Record<string, string | undefined>;
  }>;
}

try {
  const descriptor = JSON.parse(readFileSync(resolve(pluginHome, 'service.pm2.json'), 'utf8')) as Pm2Descriptor;
  const [service] = descriptor.apps;
  const expectedScript = resolve(pluginHome, 'dist/service/server.js');
  if (!service || service.name !== 'botmux-plugin-card-confirmation' || service.script !== expectedScript
      || service.env?.BOTMUX_PLUGIN_ID !== 'card-confirmation'
      || !service.env.BOTMUX_PLUGIN_CARD_ACTION_TOKEN || Number(service.env.PORT) !== 19361) {
    throw new Error('Unexpected Botmux service descriptor');
  }
  // Fail on an occupied port instead of registering some other server as this plugin.
  const probe = createServer();
  await new Promise<void>((ok, fail) => { probe.once('error', fail); probe.listen(19361, '127.0.0.1', ok); });
  await new Promise<void>(ok => probe.close(() => ok()));
  child = spawn(process.execPath, [expectedScript], {
    cwd: service.cwd, env: { ...process.env, ...service.env }, stdio: ['ignore', 'inherit', 'inherit'],
  });
  childExit = new Promise<number | null>(ok => {
    child!.once('exit', code => ok(code));
    child!.once('error', () => ok(1));
  });
  child.once('error', error => { console.error(error.message); process.exitCode = 1; });
  for (const signal of ['SIGTERM', 'SIGINT'] as const) process.on(signal, () => child?.kill('SIGTERM'));
  let healthy = false;
  for (let i = 0; i < 30; i++) {
    if (child.exitCode !== null) throw new Error('Callback service exited before readiness');
    try {
      const response = await fetch('http://127.0.0.1:19361/health', { signal: AbortSignal.timeout(1000) });
      const body = await response.json() as { ok: boolean; pid: number };
      healthy = response.ok && body.ok === true && body.pid === child.pid;
    } catch { /* retry until deadline */ }
    if (healthy) break;
    await delay(100);
  }
  if (!healthy) throw new Error('Callback service readiness failed');
  // Publish truthful gateway routing metadata only after this exact child is healthy.
  const tmp = `${metadataPath}.${process.pid}.tmp`;
  writeFileSync(tmp, JSON.stringify({
    pluginId: 'card-confirmation', version: '0.1.0',
    runtimeDir: resolve(pluginHome, 'dist'), status: 'online', port: 19361, pid: child.pid,
    manager: 'foreground-compatibility-runner', updatedAt: new Date().toISOString(),
  }), { mode: 0o600 });
  renameSync(tmp, metadataPath);
  console.log(JSON.stringify({ ready: true, pluginId: 'card-confirmation', pid: child.pid, port: 19361 }));
  process.exitCode = (await childExit) ?? 0;
} finally {
  if (child && child.exitCode === null) { child.kill('SIGTERM'); await childExit; }
  cleanup();
}
